project:
  type: book

book:
  title: "Automated Fisheries Data Management System"
  author: "Andrei Stoian"
  date: "10/27/2024"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-data-reception.qmd
    - 03-data-preparation.qmd
    - 04-system-architecture.qmd
    - 05-evaluation.qmd
    - 06-implementation.qmd
    - appendix-a.qmd
    - appendix-b.qmd
    - appendix-c.qmd

format:
  html:
    theme: flatly
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    toc: true
    toc-depth: 3
    number-sections: true

execute:
  echo: true
  warning: false
  message: false

bibliography: references.bib
