name: Quarto Publish

on:
  push:
    branches:
      - main  # or master, depending on your setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install renv and restore dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Render Book
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
          # This adds the .nojekyll file to disable Jekyll processing
          keep_files: .nojekyll
