name: Quarto Publish

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Quarto
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Set up a writable R library path
      - name: Set up R library path
        run: |
          mkdir -p ~/R/library
          echo 'R_LIBS_USER="~/R/library"' > ~/.Renviron

      # Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      # Install renv and restore dependencies
      - name: Install renv and restore dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      # Render the Quarto book
      - name: Render Book
        run: quarto render

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
          keep_files: .nojekyll
