name: Quarto Publish

on:
  push:
    branches:
      - main  # Adjust if you're using a different default branch (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Quarto
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Install system dependencies (e.g., libcurl if needed)
      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      # Install renv and restore dependencies (for R projects)
      - name: Install renv and restore dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      # Render the Quarto book
      - name: Render Book
        run: quarto render

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: .nojekyll  # Prevent Jekyll from processing Quarto output
